services:
  - type: web
    name: paimon-server
    env: python
    plan: free
    region: oregon
    buildCommand: pip install --constraint constraints.txt -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: AUTH_TOKEN
        sync: false
      - key: MEGA_EMAIL
        sync: false
      - key: MEGA_PASSWORD
        sync: false
    healthCheckPath: /ping
