services:
  - type: web
    name: paimon-server
    runtime: python
    plan: free
    buildCommand: pip install --constraint constraints.txt -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: AUTH_TOKEN
        sync: false
      - key: MEGA_EMAIL
        sync: false
      - key: MEGA_PASSWORD
        sync: false
    healthCheckPath: /ping
